name: Feature request
description: Have a Idea? Post it here.
title: "[FEATURE REQUEST]: "
labels: ["enhancement"]
assignees: 
  - song682
body: 
  - type: markdown
    attributes:
      value: |
        Have a idea that promotes this mod?
  - type: input
    id: description
    attributes:
      label: A concentrated descriptions about you ideas.
    validations:
      required: true
  - type: textarea
    id: ideas-or-imaginations
    attributes:
      label: What do you want this mod do?
      description: |
          Describe your idea or expected behavior.\
          Also tell us what you expected to happen.
      placeholder: |
        1. I want to ......
        2. I want to ......
        3. I want to ......
    validations:
       required: true
